# Restrict the length of each line of code to 90 characters. Enforcing this is important
# as many developers are working on smaller screens, or split screens. Having to scroll
# to read a full line of code makes code harder to read and more frustrating to work with.
Metrics/LineLength:
  # I've found that 90 is a suitable limit. Many developers balk at the 80 character
  # default.
  Max: 90
  Exclude:
    # Excludes the spec helper, since this boilerplate file has comments that are much
    # longer.
    - 'spec/spec_helper.rb'

# Restrict the number of lines of code that may be within a block of code. This should
# force developers to break their code into smaller discrete methods or objects.
Metrics/BlockLength:
  # Exclude specs, since those are defined as large blocks of code
  Exclude:
    - 'spec/**/*'
